default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: project-dev

test:
  <<: *default
  database: project-test
